# Generated by Django 5.2.7 on 2025-10-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kg', max_digits=5)),
                ('estatura', models.DecimalField(decimal_places=2, help_text='Estatura en cm', max_digits=5)),
                ('descripcion', models.TextField()),
                ('region', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
            ],
        ),
    ]
